services:
  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
    environment:
      - REDIS_ARGS=--loadmodule /usr/lib/redis/modules/redisearch.so